# Generated by Django 3.2.8 on 2021-11-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('problem_type', models.CharField(default='default type', max_length=100)),
                ('problem_statement', models.TextField(default='default statement', max_length=1000)),
                ('solution', models.CharField(default='default solution', max_length=10)),
                ('explanation', models.TextField(default='default explanation', max_length=1000)),
                ('problemSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='prob.problemset')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.TextField(default='choice1', max_length=1000)),
                ('choice2', models.TextField(default='choice2', max_length=1000)),
                ('choice3', models.TextField(default='choice3', max_length=1000)),
                ('choice4', models.TextField(default='choice4', max_length=1000)),
                ('problems', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_choice', to='prob.problems')),
            ],
        ),
    ]
