# Generated by Django 3.2.9 on 2021-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemsetcomment',
            old_name='date',
            new_name='created_time',
        ),
    ]
