# Generated by Django 3.2.7 on 2021-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsetcomment',
            name='content',
            field=models.TextField(default='default content', max_length=1000),
        ),
    ]
