# Generated by Django 3.2.7 on 2021-11-09 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0002_auto_20211108_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='type',
        ),
        migrations.AlterField(
            model_name='problemset',
            name='recommender',
            field=models.ManyToManyField(blank=True, related_name='recommended_problem', to='prob.UserStatistics'),
        ),
        migrations.AlterField(
            model_name='solved',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_user', to='prob.problemset'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='default content', max_length=1000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comment', to='prob.userstatistics')),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='prob.problemset')),
            ],
        ),
    ]
