# Generated by Django 3.2.6 on 2021-10-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0002_auto_20211028_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastActiveDays', models.IntegerField()),
            ],
        ),
    ]
