# Generated by Django 3.2.7 on 2021-11-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0003_auto_20211109_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
