# Generated by Django 3.2.6 on 2021-10-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0003_userstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='lastActiveDays',
            field=models.IntegerField(default=0),
        ),
    ]
