# Generated by Django 3.2.7 on 2021-11-08 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0003_comment_problemset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='solution',
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='recommender',
            field=models.ManyToManyField(blank=True, to='prob.UserStatistics'),
        ),
    ]
