# Generated by Django 3.2.7 on 2021-11-09 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0004_auto_20211108_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='solver',
            field=models.ManyToManyField(blank=True, related_name='solved_problem', to='prob.UserStatistics'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_problem', to='prob.userstatistics'),
        ),
        migrations.AlterField(
            model_name='problemset',
            name='recommender',
            field=models.ManyToManyField(blank=True, related_name='recommended_problem', to='prob.UserStatistics'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
    ]
