# Generated by Django 3.2.7 on 2021-11-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0005_rename_type_problemset_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemset',
            old_name='date',
            new_name='created_time',
        ),
    ]
