# Generated by Django 3.2.7 on 2021-11-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob', '0005_auto_20211109_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_problem', to='prob.userstatistics'),
        ),
    ]
